const USER='jessytorres';const PASS='070291';const authKey='jessy_admin_session';const dataKey='jessy_clients_v1';const reviewKey='jessy_reviews_v1';
const loginView=document.getElementById('loginView'),app=document.getElementById('app');function openApp(){loginView.classList.add('hidden');app.classList.remove('hidden');renderClients();renderReviews()}if(sessionStorage.getItem(authKey)==='1')openApp();
document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const u=document.getElementById('username').value.trim(),p=document.getElementById('password').value;const err=document.getElementById('loginError');if(u===USER&&p===PASS){sessionStorage.setItem(authKey,'1');err.textContent='';openApp()}else err.textContent='Usuário ou senha incorretos.'});document.getElementById('logout').addEventListener('click',()=>{sessionStorage.removeItem(authKey);location.reload()});
let clients=JSON.parse(localStorage.getItem(dataKey)||'[]');function money(v){return Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function birthday(d){return new Date(d+'T12:00:00').toLocaleDateString('pt-BR')}function renderClients(){const q=(document.getElementById('search')?.value||'').toLowerCase();const rows=document.getElementById('clientRows');const filtered=clients.filter(c=>c.name.toLowerCase().includes(q));rows.innerHTML=filtered.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${money(c.value)}</td><td>${birthday(c.birthday)}</td><td><button class="delete" data-id="${c.id}">Excluir</button></td></tr>`).join('');document.getElementById('emptyClients').style.display=filtered.length?'none':'block';renderBirthdays();const revenue=clients.reduce((s,c)=>s+Number(c.value),0);document.getElementById('statClients').textContent=clients.length;document.getElementById('statRevenue').textContent=money(revenue);document.getElementById('statBirthdays').textContent=clients.filter(c=>c.birthday).length;document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>{clients=clients.filter(c=>c.id!==b.dataset.id);save();renderClients()})}function save(){localStorage.setItem(dataKey,JSON.stringify(clients))}function esc(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.getElementById('clientForm').addEventListener('submit',e=>{e.preventDefault();clients.push({id:crypto.randomUUID(),name:document.getElementById('clientName').value.trim(),value:document.getElementById('clientValue').value,birthday:document.getElementById('clientBirthday').value});save();e.target.reset();renderClients()});document.getElementById('search').addEventListener('input',renderClients);
document.getElementById('exportCsv').addEventListener('click',()=>{const csv=['Nome,Valor pago,Aniversário',...clients.map(c=>`"${c.name.replace(/"/g,'""')}","${Number(c.value).toFixed(2).replace('.',',')}","${birthday(c.birthday)}"`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:'text/csv;charset=utf-8'}));a.download='clientes-jessy-unhas.csv';a.click();URL.revokeObjectURL(a.href)});
function renderReviews(){const rs=JSON.parse(localStorage.getItem(reviewKey)||'[]');document.getElementById('statReviews').textContent=rs.length;const box=document.getElementById('adminReviews');box.innerHTML=rs.length?rs.slice().reverse().map(r=>`<article class="admin-review"><b>${esc(r.name)} · ${r.date}</b><div class="stars">${'★'.repeat(r.stars)}${'☆'.repeat(5-r.stars)}</div><p>${esc(r.text)}</p></article>`).join(''):'<div class="empty">Nenhuma avaliação cadastrada.</div>'}document.getElementById('clearReviews').addEventListener('click',()=>{if(confirm('Apagar todas as avaliações deste navegador?')){localStorage.removeItem(reviewKey);renderReviews()}});

function renderBirthdays(){
 const box=document.getElementById('birthdayList'); if(!box) return;
 const now=new Date(); const currentYear=now.getFullYear();
 const upcoming=clients.filter(c=>c.birthday).map(c=>{
   const parts=c.birthday.split('-').map(Number);
   let d=new Date(currentYear,parts[1]-1,parts[2],12);
   if(d<new Date(now.getFullYear(),now.getMonth(),now.getDate(),12)) d.setFullYear(currentYear+1);
   return {...c,date:d};
 }).sort((a,b)=>a.date-b.date).slice(0,6);
 box.innerHTML=upcoming.length?upcoming.map(c=>`<div class="birthday-item"><div><strong>${esc(c.name)}</strong><span>${c.date.toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})}</span></div><b>🎂</b></div>`).join(''):'<div class="empty">Nenhum aniversário cadastrado.</div>';
}
